# Generated by Django 4.1.7 on 2023-03-26 07:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            """CREATE SCHEMA IF NOT EXISTS content;
    ALTER ROLE app SET search_path TO content,public;
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";"""
        ),
        migrations.CreateModel(
            name="EmailTemplateContent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField(verbose_name="title")),
                ("text", models.TextField(verbose_name="text")),
            ],
            options={
                "verbose_name": "Email template",
                "verbose_name_plural": "Email templates",
                "db_table": 'content"."email_template',
            },
        ),
        migrations.CreateModel(
            name="EmailTemplateImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="Image")),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.emailtemplatecontent",
                        verbose_name="Email template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email template picture",
                "verbose_name_plural": "Email templates pictures",
                "db_table": 'content"."email_template_picture',
            },
        ),
    ]
