# Generated by Django 4.1.7 on 2023-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0002_emailtemplatecontent_admin_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplatecontent",
            name="admin_title",
            field=models.CharField(
                default="admin title", max_length=255, verbose_name="Admin name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailtemplatecontent",
            name="text",
            field=models.TextField(verbose_name="HTML"),
        ),
        migrations.AlterField(
            model_name="emailtemplateimage",
            name="admin_title",
            field=models.CharField(
                default="admin title", max_length=255, verbose_name="Admin name"
            ),
            preserve_default=False,
        ),
    ]
