# Generated by Django 4.1.7 on 2023-04-22 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0003_alter_emailtemplatecontent_admin_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplatecontent",
            name="title",
            field=models.TextField(verbose_name="E-mail subject"),
        ),
        migrations.CreateModel(
            name="EmailTemplateContext",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "admin_title",
                    models.CharField(max_length=255, verbose_name="Admin name"),
                ),
                (
                    "custom_title",
                    models.CharField(max_length=100, verbose_name="Title"),
                ),
                (
                    "custom_subtitle",
                    models.CharField(max_length=300, verbose_name="Subtitile"),
                ),
                ("custom_movieurl", models.URLField(verbose_name="Movie page URL")),
                (
                    "custom_moviename",
                    models.CharField(max_length=300, verbose_name="Movie name"),
                ),
                ("custom_text", models.TextField(verbose_name="Text")),
                (
                    "custom_cta",
                    models.CharField(
                        max_length=30, verbose_name="Call to action on button"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mailing.emailtemplatecontent",
                        verbose_name="E-mail template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email template context",
                "verbose_name_plural": "Email templates contexts",
                "db_table": 'content"."email_template_context',
            },
        ),
        migrations.CreateModel(
            name="EmailAssembled",
            fields=[
                (
                    "emailtemplatecontent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mailing.emailtemplatecontent",
                    ),
                ),
                (
                    "context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mailing.emailtemplatecontext",
                        verbose_name="E-mail context",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="EmailAssembled",
                        to="mailing.emailtemplatecontent",
                        verbose_name="E-mail template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assembled e-mail",
                "verbose_name_plural": "Assembled e-mails",
                "db_table": 'content"."email_assembled',
            },
            bases=("mailing.emailtemplatecontent",),
        ),
    ]
