repos:
-   repo: https://github.com/psf/black
#    rev: 22.12.0
    rev: ''
    hooks:
      - id: black
-   repo: https://github.com/pycqa/isort
    rev: ''
#    rev: 5.11.2
    hooks:
      - id: isort
-   repo: https://github.com/pycqa/flake8
    rev: ''
#    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-print
