version: '3.8'

services:
  notification_db:
    image: postgres:14
    restart: unless-stopped
    env_file:
      - ./dev.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 2s
      timeout: 2s
      retries: 5
    expose:
      - 5432
    ports:
      - "5432:5432"

  notification_app:
    image: python:3.10
    restart: unless-stopped
    env_file:
      - ./dev.env
    volumes:
      - ./app:/app
    command: >
      bash -c "pip install --upgrade pip
      && pip install --no-cache-dir -r /app/requirements.txt
      && python /app/src/manage.py migrate
      && python /app/src/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      notification_db:
        condition: service_healthy

