# Generated by Django 4.2 on 2023-04-29 11:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('html_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_templates',
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('group_id', models.TextField()),
            ],
            options={
                'verbose_name': 'Group user',
                'verbose_name_plural': 'Groups users',
                'db_table': 'groups_users',
            },
        ),
        migrations.CreateModel(
            name='IndividualNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('body', models.TextField(verbose_name='body')),
                ('delay', models.IntegerField(verbose_name='delay')),
            ],
            options={
                'verbose_name': 'Individual Notification',
                'verbose_name_plural': 'Individual Notifications',
                'db_table': 'individual_notifications',
            },
        ),
        migrations.CreateModel(
            name='MassNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('body', models.TextField(verbose_name='body')),
                ('delay', models.IntegerField(verbose_name='delay')),
                (
                    'group',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='mailer.groupuser',
                        verbose_name='group_users',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Mass Notification',
                'verbose_name_plural': 'Mass Notifications',
                'db_table': 'mass_notifications',
            },
        ),
    ]
